In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size = (5,3))
a

array([[6, 3, 0],
       [5, 7, 7],
       [2, 9, 1],
       [1, 8, 3],
       [1, 2, 8]])

In [3]:
np.unique(a)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [4]:
a[0]

array([6, 3, 0])

In [5]:
a[0][1]

3

In [9]:
a[:2]

array([[6, 3, 0],
       [5, 7, 7]])

In [11]:
a[:2, :2]

array([[6, 3],
       [5, 7]])

In [12]:
a[:1, :2]

array([[6, 3]])

In [13]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[1, 0, 0, 9, 1],
         [0, 8, 2, 0, 0],
         [4, 3, 7, 7, 2],
         [1, 4, 9, 0, 2]],

        [[1, 2, 1, 4, 7],
         [1, 8, 6, 0, 9],
         [1, 1, 4, 9, 8],
         [3, 6, 9, 2, 1]],

        [[1, 4, 6, 1, 2],
         [9, 1, 2, 8, 8],
         [4, 5, 3, 6, 3],
         [1, 7, 3, 6, 7]]],


       [[[5, 8, 1, 9, 5],
         [8, 5, 8, 3, 6],
         [3, 7, 3, 5, 4],
         [2, 6, 2, 2, 6]],

        [[8, 5, 8, 4, 3],
         [6, 4, 8, 2, 6],
         [6, 4, 1, 1, 3],
         [6, 9, 1, 5, 9]],

        [[6, 8, 6, 2, 8],
         [4, 2, 9, 3, 7],
         [6, 2, 6, 4, 9],
         [9, 2, 8, 6, 3]]]])

In [14]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [15]:
# get the 1st 4 number of inner most arrays
a4[:, :, :, :1]

array([[[[1],
         [0],
         [4],
         [1]],

        [[1],
         [1],
         [1],
         [3]],

        [[1],
         [9],
         [4],
         [1]]],


       [[[5],
         [8],
         [3],
         [2]],

        [[8],
         [6],
         [6],
         [6]],

        [[6],
         [4],
         [6],
         [9]]]])

# Manipulatin Data

In [16]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [18]:
twos = np.random.randint(1, 10, size= (1,3))
twos

array([[2, 5, 7]])

In [19]:
ones * twos

array([[2., 5., 7.]])

In [20]:
type(twos)

numpy.ndarray

In [21]:
twos.dtype

dtype('int64')

In [22]:
a1 = np.array([2,3,4])
a1

array([2, 3, 4])

In [24]:
a1 * twos

array([[ 4, 15, 28]])

In [25]:
twos / a1

array([[1.        , 1.66666667, 1.75      ]])

In [26]:
np.std(a1)

0.816496580927726

In [27]:
np.sum(twos)

14

In [28]:
np.var(a1)

0.6666666666666666

In [31]:
np.sqrt(np.var(a1))

0.816496580927726