In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5, 3))
mat2 = np.random.randint(10, size = (5, 3))

In [3]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [4]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [5]:
# Element-wise multiplication (Hadamard Product)

mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [6]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [7]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [8]:
# Dot Product

mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Dot Product Example

In [9]:
np.random.seed(0)

# Number of jar sold
sales_amounts = np.random.randint(20, size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [10]:
weekly_sales = pd.DataFrame(sales_amounts, 
                            index = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'],
                            columns = ['Almond Butter','Peanut Butter', 'Cashew Butter'])

weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [11]:
# Create prices array
price = np.array([10, 8, 12])
price

array([10,  8, 12])

In [12]:
price.shape

(3,)

In [13]:
butter_price = pd.DataFrame(price.reshape(1,3),
                           index = ['Price'],
                           columns = ['Almond Butter','Peanut Butter', 'Cashew Butter'])

butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [14]:
total_sales = price.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [15]:
butter_price.shape, weekly_sales.shape

((1, 3), (5, 3))

In [16]:
butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [17]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [18]:
daily_sales = butter_price.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [19]:
weekly_sales['Total ($)'] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142