In [1]:
import numpy as np

# Comparison

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
a2 = np.random.randint(10, size = (2,3))
a2

array([[3, 6, 9],
       [6, 0, 7]])

In [6]:
a1 > a2

array([[False, False, False],
       [False,  True, False]])

In [8]:
a1 >= a2

array([[False, False, False],
       [False,  True, False]])

In [9]:
a1 == a2

array([[False, False, False],
       [False, False, False]])

# Sorting

In [12]:
np.random.seed(0)
random_array = np.random.randint(10, size = (3, 5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [13]:
random_array.shape

(3, 5)

In [15]:
np.sort(random_array)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [16]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [18]:
# sorting index
np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]])

In [19]:
np.argmax(a1)

2

In [20]:
np.argmin(a1)

0

In [22]:
np.argmax(random_array)

5

In [24]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [23]:
np.argmax(random_array, axis = 0)

array([1, 2, 2, 2, 0])

In [25]:
np.argmax(random_array, axis = 1)

array([4, 0, 2])