In [1]:
import numpy as np

# Datatypes & Attribute

In [2]:
# NumPy's main datatype is ndarry
a1 = np.array([2,3,5,6,7,8,1])
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([
    [1,3,5],
    [4,6,3],
])

a3 = np.array([
    [
    [3,4,3],
    [5,2,6],
    [1,7,3]
],
    [[3,4,3],
    [5,2,6],
    [1,7,3]],
])

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(7, 6, 18)

# Creating DataFrame from numpy array

In [14]:
import pandas as pd

In [16]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  3  5
1  4  6  3

# Creating Numpy Array

In [17]:
sample_array = np.array([1,2,4,])
sample_array

array([1, 2, 4])

In [18]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size = (3,5))
random_array

array([[3, 3, 8, 1, 1],
       [3, 0, 2, 8, 5],
       [1, 8, 8, 1, 6]])

In [24]:
random_array.size

15

In [25]:
random_array1 = np.random.random((5,3))
random_array1

array([[0.83716762, 0.77540656, 0.02212927],
       [0.89738894, 0.44772091, 0.91498937],
       [0.54383659, 0.25109799, 0.04278492],
       [0.05207007, 0.70496972, 0.37122363],
       [0.07115246, 0.40932797, 0.56236798]])

In [26]:
random_array2 = np.random.rand(5,3)
random_array2

array([[0.69592957, 0.45344296, 0.16215072],
       [0.18366283, 0.36586822, 0.43795197],
       [0.47501429, 0.48892806, 0.69010711],
       [0.46107649, 0.12913789, 0.31749333],
       [0.97642957, 0.77843165, 0.9608163 ]])

# To stop randomizig a variable value everytime is run. we use .seed()

In [38]:
np.random.seed(0)

a4 = np.random.randint(10, size=(3,2))
a4

array([[5, 0],
       [3, 3],
       [7, 9]])

In [39]:
a4

array([[5, 0],
       [3, 3],
       [7, 9]])